%YAML:1.0

camera:
  intrinsics:
    fx: 718.856   #  7.188560000000e+02
    fy: 718.856   #  7.188560000000e+02
    cx: 607.1928  #  6.071928000000e+02
    cy: 185.2157  #  1.852157000000e+02
    # KITTI get P0 values from calib.txt
    #  fx = P0.values[0]
    #  fy = P0.values[5]
    #  cx = P0.values[2]
    #  cy = P0.values[6]

optimization:
  use_clahe: 1

estimation:
  min_pts: 8
  min_inliers: 16
  essential_prob: 0.99
  essential_threshold: 1.0

tracking:
  # sift|orb - orb is default | sift + flann_knn, sift + lkof, orb + lkof are a very good combos. sift + flan_knn is a bit slow
  feature_type: orb

  # -------------------------------------------------------------- #
  # ORB
  # bf|bf_knn|flann|flann_knn|lkof - bf is default, lkof - LK Optical Flow
  orb_feature_matcher: lkof
  orb_max_extract_features: 2000
  orb_max_sorted_simple_features: 500
  orb_min_valid_features: 20
  # Smaller ratio = stricter ambiguity check
  orb_knn_dist_k: 0.50
  # ORB Hamming Distance: 20–40
  orb_max_dist_simple: 20
  # high precision lkof params: 50, 0.001
  # Robust lkof params: 20, 0.03
  orb_lkof_criteria_max_it: 50
  orb_lkof_criteria_eps: 0.001

  # -------------------------------------------------------------- #
  # SIFT
  # bf|bf_knn|flann|flann_knn|lkof - bf is default, lkof - LK Optical Flow
  sift_feature_matcher: flann_knn
  sift_max_extract_features: 2000
  sift_max_sorted_simple_features: 500
  sift_min_valid_features: 20
  # Smaller ratio = stricter ambiguity check
  sift_knn_dist_k: 0.85
  # SIFT L2 Distance: 100–250
  sift_max_dist_simple: 80
  # high precision lkof params: 50, 0.001
  # Robust lkof params: 20, 0.03
  sift_lkof_criteria_max_it: 20
  sift_lkof_criteria_eps: 0.03
