%YAML:1.0

camera:
  intrinsics:
    fx: 718.856   #  7.188560000000e+02
    fy: 718.856   #  7.188560000000e+02
    cx: 607.1928  #  6.071928000000e+02
    cy: 185.2157  #  1.852157000000e+02
    # KITTI get P0 values from calib.txt
    #  fx = P0.values[0]
    #  fy = P0.values[5]
    #  cx = P0.values[2]
    #  cy = P0.values[6]

optimization:
  use_clahe: 1

estimation:
  min_pts: 8
  min_inliers: 16
  essential_prob: 0.99
  essential_threshold: 1.0

tracking:
  feature_type: orb

  # ORB
  # orb_max_distance:   20     # ORB Hamming Distance: 20–40
  orb_knn_distance_k: 0.5 # Smaller ratio = stricter ambiguity check
  orb_max_extract_features: 2000
  orb_max_sorted_features:  100
  orb_min_valid_features:   20

  # sift_max_distance: 100        # ORB L2 Distance: 100–250
  sift_knn_distance_k: 0.5 # Smaller ratio = stricter ambiguity check
  sift_max_extract_features: 2000
  sift_max_sorted_features: 100
  sift_min_valid_features: 20

  surf_max_distance: 0.1        # ORB L2 Distance: 0.1–0.3
  super_point_max_distance: 0.2 # ORB L2/Cosine Distance: 0.2–0.6
